GET http://localhost:3000/test
Accept: application/json

###
POST http://localhost:3000/1/2/3/4
Content-Type: application/json

{
  "name": "test",
  "age": 2
}

###
WEBSOCKET ws://localhost:3000/test/1
Sec-WebSocket-Protocol: json

{
  "name": "test",
  "age": 2
}

### ZZZ
WEBSOCKET ws://localhost:3000/zzzzz
Sec-WebSocket-Protocol: json

{
  "name": "test",
  "age": 2
}
